// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs8G52Ptpazmzl_0xIEK2RTCI6R3awNec',
    appId: '1:543326558404:web:6e16aab0dc4765e7b79191',
    messagingSenderId: '543326558404',
    projectId: 'note-fba38',
    authDomain: 'note-fba38.firebaseapp.com',
    storageBucket: 'note-fba38.appspot.com',
    measurementId: 'G-GQNE389BDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpHaXlw8qanoZavvg_WoykdkeCT4RzDw4',
    appId: '1:543326558404:android:2adf4ca71e464409b79191',
    messagingSenderId: '543326558404',
    projectId: 'note-fba38',
    storageBucket: 'note-fba38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD4fy-WFqBPFpnms47cnNoa4AU0SR4qT8',
    appId: '1:543326558404:ios:a5a0232c1c364530b79191',
    messagingSenderId: '543326558404',
    projectId: 'note-fba38',
    storageBucket: 'note-fba38.appspot.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD4fy-WFqBPFpnms47cnNoa4AU0SR4qT8',
    appId: '1:543326558404:ios:9f94b9f4da7780dbb79191',
    messagingSenderId: '543326558404',
    projectId: 'note-fba38',
    storageBucket: 'note-fba38.appspot.com',
    iosBundleId: 'com.example.noteApp.RunnerTests',
  );
}
